package definitions

import (
	"fmt"
	"maps"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/Furyfree/nimbus/internal/rpm"
)

const VersionlockPath = "/etc/dnf/versionlock.toml"

// PackageConstraint selects a stable numeric version family at RPM epoch zero.
type PackageConstraint struct {
	Package string `json:"package"`
	Name    string `json:"name"`
	Family  string `json:"family"`
	Lower   string `json:"lower"`
	Upper   string `json:"upper"`
}

var familyRE = regexp.MustCompile(`^(0|[1-9][0-9]{0,8})(\.(0|[1-9][0-9]{0,8}))?\.\*$`)

func parseConstraint(key, family string) (PackageConstraint, error) {
	c := PackageConstraint{Package: key, Family: family}
	ref, err := ParseRef(key)
	if err != nil || ref.Canonical() != key || ref.Prefix == PrefixFlatpak {
		return c, fmt.Errorf("constraint key %q must be a canonical RPM package reference", key)
	}
	name, arch := rpm.SplitRequest(ref.Name)
	if arch != "" || !familyRE.MatchString(family) {
		return c, fmt.Errorf("constraint %s requires an unqualified RPM name and a numeric family like 5.* or 0.56.*", key)
	}
	c.Name = name
	parts := strings.Split(strings.TrimSuffix(family, ".*"), ".")
	c.Lower = "0:" + strings.Join(parts, ".")
	n, _ := strconv.Atoi(parts[len(parts)-1])
	parts[len(parts)-1] = strconv.Itoa(n + 1)
	c.Upper = "0:" + strings.Join(parts, ".") + "~"
	return c, nil
}

func resolveConstraints(checkout *Checkout, machine *Machine, r *Resolved, errs *ErrorList) {
	where := "machines/" + machine.ID + ".toml package_constraints"
	for _, key := range slices.Sorted(maps.Keys(machine.PackageConstraints)) {
		c, err := parseConstraint(key, machine.PackageConstraints[key])
		if err != nil {
			errs.Add(where, "%v", err)
			continue
		}
		if !slices.ContainsFunc(r.Packages, func(p ResolvedPackage) bool { return p.Canonical == key }) {
			errs.Add(where, "%s is not a selected package", key)
			continue
		}
		r.Constraints = append(r.Constraints, c)
	}
	if slices.ContainsFunc(r.Files, func(f ResolvedFile) bool { return f.Target == VersionlockPath }) {
		errs.Add(where, "%s is reserved for generated package constraints", VersionlockPath)
		return
	}
	if len(r.Constraints) == 0 {
		return
	}
	if value, exists := checkout.Root_.DNF["excludepkgs"]; exists {
		if _, ok := value.(string); !ok {
			errs.Add(where, "dnf.excludepkgs must be a string when constraints are selected")
		}
	}
	var content strings.Builder
	content.WriteString("# Generated by Nimbus from machine package_constraints.\nversion = \"1.0\"\n")
	for _, c := range r.Constraints {
		fmt.Fprintf(&content, "\n[[packages]]\nname = %q\ncomment = %q\nconditions = [{key = \"evr\", comparator = \">=\", value = %q}, {key = \"evr\", comparator = \"<\", value = %q}]\n", c.Name, c.Package+" "+c.Family, c.Lower, c.Upper)
	}
	r.Files = append(r.Files, ResolvedFile{Target: VersionlockPath, Component: "package-constraints", Owner: "root", Group: "root", Mode: "0644", Content: []byte(content.String())})
}

// Matches checks numeric family membership, not RPM version ordering. Native
// DNF owns comparisons and transactions; this exposes already-installed drift.
func (c PackageConstraint) Matches(evr string) bool {
	if epoch, rest, ok := strings.Cut(evr, ":"); ok {
		if epoch != "0" {
			return false
		}
		evr = rest
	}
	version, _, _ := strings.Cut(evr, "-")
	for _, part := range strings.Split(version, ".") {
		if part == "" || strings.ContainsFunc(part, func(r rune) bool { return r < '0' || r > '9' }) {
			return false
		}
	}
	prefix := strings.TrimSuffix(c.Family, ".*")
	return version == prefix || strings.HasPrefix(version, prefix+".")
}
