schema = 1
id = "snapper"
packages = ["snapper"]

[[files]]
source = "etc/snapper/config-templates/nimbus"
owner = "root"
group = "root"
mode = "0644"

[[services]]
unit = "snapper-cleanup.timer"
enabled = true
running = true
